### PR TITLE
Setup a SecurityGroupPolicy

### PR DESCRIPTION
**Pull request by Nalum**
This change will allow setting up an [AWS EKS `SecurityGroupPolicy`](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html#deploy-securitygrouppolicy) against the `ServiceAccount` used by the `tf-controller` `POD`s.

If supplied the `POD`s will be started and run under the specific AWS Security Groups that are passed in the list.

### CODE REVIEW

**Comment by phoban01** [comment]
Do we have an issue describing why this is required?

**Comment by phoban01** [comment]
@Nalum Seems a bit specific to AWS; but would be good to have some context in the description or in an issue 🙂 .

**Comment by Nalum** [comment]
@phoban01 I've updated the description, will think a bit more about info that I can add to it.

As to being specific to AWS, it is very much so.

**Review by tomhuang12 — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
