### PR TITLE
use retry policy for grpc connection

### PR DESCRIPTION
**Pull request by chanwit**
This PR gives a block of 10 secs before gRPC going connection timed out.

### CODE REVIEW

**Review by phoban01 — COMMENTED** [review]
@chanwit You could pass a retry policy `grpc.WithDefaultServiceConfig` to `grpc.Dial` rather than using context timeout. Full example is here: grpc.WithDefaultServiceConfig

What do you think?

**Comment by chanwit** [comment]
That's super cool! I'll re-write it.

**Review by phoban01 — APPROVED** [review]
LGTM, nice work @chanwit

**Comment by chanwit** [comment]
seems we need to rewrite whole E2E tests in Golang.

**Pull request merged**
