### PR TITLE
feat: use RUNTIME_NAMESPACE for resources if namespace is not defined

### LINKED ISSUE #765: If `namespace` is not defined for a resource in the ConfigMap, use the runtime namespace.

### LINKED ISSUE #767: The configmap name would be default to $runtime-namespace/branch-planner.

### PR DESCRIPTION
**Pull request by yitsushi**
If `RUNTIME_NAMESPACE` is not defined, it falls back to `flux-system`.

Closes #765
Closes #767

References:
* https://github.com/weaveworks/tf-controller/issues/765

### CODE REVIEW

**Comment by yitsushi** [comment]
force-push: rebase from main + resolve conflict

**Review by chanwit — APPROVED** [review]
LGTM

**Comment by chanwit** [comment]
@yitsushi Could you help bump `libcrypto3=3.1.1-r2` in every Dockerfile please?
Trivy scanning failture.

**Comment by yitsushi** [comment]
I think this one closes #767 tooi

**Pull request merged**
