### PR TITLE
Feature/add tfvarsfiles spec

### PR DESCRIPTION
**Pull request by itamar-marom**
#338 
With this PR, we can add more `.tfvars` files to the Terraform object.
those files are only files located in the `Terraform.spec.sourceRef` and the path is relative to its root.
- Also, I upgraded the docker files base image to version 3.16.2 in order for it to build correctly.

Works the same as terraform's `-var-file`: https://developer.hashicorp.com/terraform/language/values/variables#variable-definition-precedence

Example:
```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: 
spec:
    path: deployments/eks/platform
    fileMappings: # File mappings will also be in the tfVarsFiles
        - location: "workspace"
           path: "another.tfvars"
           secretRef:
               name: ...
               key: ...
    tfVarsFiles: # This is the new field. It holds the precedence + paths
        - deployments/eks/platform/default.tfvars # From sourceRef
        - deployments/eks/platform/another.tfvars # From fileMappings
        - environments/platform/env.tfvars # From sourceRef
    sourceRef: # GitRepository as source
  	kind: GitRepository
        name: helloworld
        namespace: flux-system
```

### CODE REVIEW

**Comment by svengreb** [comment]
@yitsushi I don't ping people often, but I saw that [you've been added as an active maintainer](https://github.com/weaveworks/tf-controller/commit/37ac15c6) recently which is great since I like and use this controller a lot!

Is there any chance that this PR can be reviewed in the near future? If you need support to test and verify it let me know since this feature is definitely one that is required to make Terraform modules in k8s with Flux way more dynamic and I currently use way too _hacky_ workarounds to inject files into the (dynamic) workspace path inside a container.

**Comment by itamar-marom** [comment]
@svengreb I'm into fixing this PR if this time it will be reviewed 😄

**Comment by yitsushi** [comment]
screenshot
It seems I already started it but got distracted.

If the branch gets updated (so I don't have to figure out what is outdated and what's not), yes I'll review it (at least try and ask questions if something is not clear).

**Comment by svengreb** [comment]
@itamar-marom I figured you wouldn't want to drop your implementation 😄
@yitsushi Nice and thanks for taking care of this project!

**Comment by itamar-marom** [comment]
Hi @yitsushi @svengreb 
I opened a new PR with this feature (rebase was too much for me this time haha).
Feature and tests added. Tests passed. it's ready for review and merge 😄 
#1185 
https://github.com/weaveworks/tf-controller/pull/1185

**Pull request closed without merging**
