### PR TITLE
fsequeira1's custom backend

### PR DESCRIPTION
**Pull request by chanwit**
This PR is a finishing of @fsequeira1's custom backend.
I've added localstack to the test case to make it work.

Replaces #277
Fixes ##97

### CODE REVIEW

**Review by fsequeira1 — APPROVED** [review]
LGTM

**Comment by chanwit** [comment]
Thank you so much @fsequeira1 for starting this work.

**Comment by mjazwiecki** [comment]
great development! 
does it support also azurerm storage account backend?

**Comment by chanwit** [comment]
@mjazwiecki yes, together with the newly landed the `.spec.backendConfigsFrom` feature, I think it virtually supports every backend Terraform does.

**Pull request merged**
