### PR TITLE
test: disable flaky tests

### LINKED ISSUE #856: Fix or remove flaky tests
We regularly get red builds due to tests that are flaky. This slows us down and makes the tests lest trustworthy so we should either fix those or remove them altogether.

- [ ] Test_000071_varsfrom_secret_with_varkeys_rename_and_controlled_outputs_test ([logs](https://github.com/weaveworks/tf-controller/actions/runs/5822640869/job/15787711479))
- [ ] Test_000260_runner_pod_test_env_vars_valueFrom_secretRef ([logs](https://github.com/weaveworks/tf-controller/actions/runs/5820837878/job/15782062023))

### PR DESCRIPTION
**Pull request by yitsushi**
Closes #856

References:
* https://github.com/weaveworks/tf-controller/issues/856

### CODE REVIEW

**Comment by yitsushi** [comment]
```
❯ echo "stable:"; \
    grep -L "build flaky" controllers/*_test.go | sed -e 's/^/  - /'; \
    echo "flaky:"; \
    grep -l "build flaky" controllers/*_test.go | sed -e 's/^/  - /';

stable:
  - controllers/get_runner_pod_object_key_test.go
  - controllers/object_encode_test.go
  - controllers/source_predicate_test.go
  - controllers/suite_test.go
  - controllers/tc000010_no_outputs_test.go
  - controllers/tc000011_bad_tar_gz_no_outputs_test.go
  - controllers/tc000012_src_bucket_no_outputs_test.go
  - controllers/tc000013_source_not_found_test.go
  - controllers/tc000014_artifact_not_found_test.go
  - controllers/tc000015_depends_on_cross_ns_denied_test.go
  - controllers/tc000015_source_cross_ns_denied_test.go
  - controllers/tc000020_with_backend_no_outputs_test.go
  - controllers/tc000020_with_workspace_no_outputs_test.go
  - controllers/tc000030_plan_only_no_outputs_test.go
  - controllers/tc000074_varsfrom_accepts_many_secrets_with_last_supplied_key_precedence_test.go
  - controllers/tc000082_varsfrom_accepts_many_configmaps_with_last_supplied_key_precedence_test.go
  - controllers/tc000100_applied_should_tx_to_plan_when_source_changed_test.go
  - controllers/tc000110_auto_applied_should_tx_to_plan_then_apply_when_source_changed_test.go
  - controllers/tc000180_should_detect_drift_test.go
  - controllers/tc000190_unsupported_source_should_error_test.go
  - controllers/tc000191_missing_source_should_error_test.go
  - controllers/tc000200_disable_drift_detection_test.go
  - controllers/tc000210_plan_encode_decode_test.go
  - controllers/tc000220_support_config_file_via_secret_test.go
  - controllers/tc000240_health_check_test.go
  - controllers/tc000300_targets_test.go
  - controllers/tc000310_node_selector_affinity_tolerations_test.go
  - controllers/tc000311_init_container_test.go
  - controllers/tc000320_vol_and_vol_mounts_test.go
  - controllers/tc000330_file_mapping_no_outputs_test.go
  - controllers/tc000340_webhooks_for_post_planning_test.go
  - controllers/tc000350_depends_on_test.go
  - controllers/tc009990_mtls_generate_creds_test.go
  - controllers/webhook_mock_test.go
flaky:
  - controllers/tc000011_workspace_no_outputs_test.go
  - controllers/tc000031_plan_only_with_showplan_as_cm_no_outputs_test.go
  - controllers/tc000040_controlled_outputs_test.go
  - controllers/tc000041_all_outputs_test.go
  - controllers/tc000042_output_name_contains_dot_test.go
  - controllers/tc000043_controlled_outputs_should_be_reconciled_test.go
  - controllers/tc000044_plan_only_mode_test.go
  - controllers/tc000050_plan_and_manual_approve_no_outputs_test.go
  - controllers/tc000051_plan_and_manual_approve_and_replan_no_outputs_test.go
  - controllers/tc000052_plan_and_manual_approve_with_files_test.go
  - controllers/tc000060_vars_and_controlled_outputs_test.go
  - controllers/tc000061_vars_hcl_input_test.go
  - controllers/tc000062_vars_hcl_test.go
  - controllers/tc000063_values_hcl_test.go
  - controllers/tc000064_values_template_hcl_test.go
  - controllers/tc000070_varsfrom_secret_and_controlled_outputs_test.go
  - controllers/tc000071_varsfrom_secret_with_varkeys_and_controlled_outputs_test.go
  - controllers/tc000072_varsfrom_optional_secret_controlled_outputs_test.go
  - controllers/tc000073_varsfrom_accepts_many_secrets_outputs_test.go
  - controllers/tc000075_varsfrom_secret_with_varkeys_rename_and_controlled_outputs_test.go
  - controllers/tc000080_varsfrom_configmap_and_controlled_outputs_test.go
  - controllers/tc000081_varsfrom_accepts_many_configmap_controlled_outputs_test.go
  - controllers/tc000090_varsfrom_override_and_controlled_outputs_test.go
  - controllers/tc000111_with_backend_s3_no_outputs_test.go
  - controllers/tc000120_delete_test.go
  - controllers/tc000121_destroy_on_delete_test.go
  - controllers/tc000130_destroy_no_outputs_test.go
  - controllers/tc000131_destroy_no_changes_test.go
  - controllers/tc000140_auto_applied_should_tx_to_plan_then_apply_when_drift_detected_test.go
  - controllers/tc000150_manual_apply_should_report_and_loop_when_drift_detected_test.go
  - controllers/tc000160_auto_applied_should_tx_to_plan_when_unrelated_source_changed_test.go
  - controllers/tc000170_if_apply_error_we_should_delete_the_plan_and_start_over_test.go
  - controllers/tc000201_auto_approve_with_disabled_drift_detection_test.go
  - controllers/tc000230_drift_detection_only_mode_test.go
  - controllers/tc000241_auto_approve_with_health_checks_test.go
  - controllers/tc000242_bad_health_checks_test.go
  - controllers/tc000260_runner_pod_test.go
  - controllers/tc000280_inventory_test.go
  - controllers/tc000290_force_unlock_test.go
```

**Comment by yitsushi** [comment]
Added a job that can be triggered manually, and automatically runs on push to main.

**Comment by yitsushi** [comment]
Follow-up: https://github.com/weaveworks/tf-controller/issues/865

**Comment by yiannistri** [comment]
@yitsushi can you provide a link to the job you've added?

**Review by yiannistri — APPROVED** [review]

**Pull request merged**
